### ISSUE TITLE
Suggested configuration for multiple services.

### ISSUE THREAD

**Issue by neilellis** [vizzbuzz/tutum-cron#1]
@stepan's suggested configuration for multiple services.

```
tutum-cron:
  image: vizzbuzz/tutum-cron
  autorestart: always
  roles:
    - global
  environment:
    CLI_CRON_SCHEDULE_1: '* * * * * php artisan clean:tmp'
    CLI_CRON_SCHEDULE_2: '* * * * * php artisan sessions:expire'
    CLI_CRON_SCHEDULE_3: '* * * * * php artisan email:digest'
  links:
    - cli
cli:
  image: myimage
```
